### ISSUE TITLE
Fujitsu waveform

### ISSUE THREAD

**Issue by simmonmt** [simmonmt/fujitsu#1]
@unreality I'm seeing the following waveform from the inside unit of my Fujitsu heatpump. Based on comments on your project, it sounds like the signal wire is expected to use the LIN bus protocol, which I **thought** (perhaps incorrectly) was logical 0 = 0v, logical 1 = >0v. This .. is not that. Before I go too much deeper, can you confirm whether these waveforms are what you expect to see coming from a Fujitsu inside unit that your unreality/FujiHeatPump project can talk to?

https://photos.app.goo.gl/KyoaFX5TXNooJLna6

Thanks

Matt

**Comment by simmonmt** [comment]
Also @jaroslawprzybylowicz because the more the merrier

**Comment by unreality** [comment]
Im certainly no electrical engineer, and basically just used @jaroslawprzybylowicz hard work to make my stuff work, plus its a long time since ive looked at this, but iirc i think the bus was held high until a controller wants to send a signal then its pulled low?

Again, i have absolutely no electrical engineering skills, so I really have no idea. The LIN controller worked so i used it :D

**Comment by jaroslawprzybylowicz** [comment]
These waveforms look nowhere close to what I would expect. The amplitude is much lower and there's a high-frequency component that is way above the 500bps. In the units I've encountered the expected waveform is rectangular with amplitude of ~12V (0-6V for low state, 6-12V for high state) and 2ms width.
It would help if you can post what kind of device you are using and where do you attach the scope. It's possible that HP cut off the communication once it didn't detect anything on the other end and what you see is just noise. Standard three-wire controller would simply ignore these waveforms as they are below the 6V threshold.

**Comment by simmonmt** [comment]
Sure. It's an ASU30RLE inside unit with about 1.5m of maybe 18AWG cable running from the inside unit to the oscilloscope probe. The cable wasn't connected to anything else, so it was like I had hooked the probes directly up to the inside unit itself. My hope is that the length cable doesn't cause too much loss or noise, as using it makes oscilloscope positioning sooo much easier.

I've updated the album with closer-in versions of the waveforms: https://photos.app.goo.gl/KyoaFX5TXNooJLna6

As you can see from the video they change over time in a very structured way so it doesn't seem like noise. Also you can see the screen refresh as it triggers at a pretty low frequency (I don't yet know how to get the scope to display the triggering frequency). 

So maybe Fujitsu came up with some clever new signalling mechanism/protocol? If so, lucky me. :-/  It would also explain why the UTY-TFNXZ2 has never been able to talk to this inside unit -- if the UTY-TFNXZ2 is expecting LIN while this unit is talking something else entirely.

**Comment by unreality** [comment]
Looking at the install manual, it seems that model allows for a 2-wire OR 3-wire wired remote, which i have not seen before in the service/install manuals before...

https://www.manualslib.com/manual/1241176/Fujitsu-Asu30rle.html?page=8#manual

**Comment by simmonmt** [comment]
Oh I'm sorry yeah I forgot to answer that. I'm attaching directly to the
three wire terminal on the inside unit. I'm not going through a UTY-XCSXZ1.
I wonder if that's what translates between whatever signal this is and LIN?
That would change things a bit.

Matt

**Comment by simmonmt** [comment]
And I'm hanging the oscilloscope off the signal (white) and ground (black) wires, leaving the 12V (red) alone

**Comment by simmonmt** [comment]
I figured it out!

@jaroslawprzybylowicz this might be something to file away just in case someone else raises the problem with you. If you/they see that balanced/AC signal, it more than likely means their inside unit has been set to use the 2-wire protocol rather than the 3-wire protocol. I assume the 2-wire protocol is meant to deliver enough power on that line to run the remote (at 2V p-p, no less) while also supporting signaling. The 3-wire protocol is the LIN bus (or I assume it is).

On the ASU30RLE system board, next to the port labeled CN12, there is a teeny tiny DIP switch. Switch it left, and you get 2-wire mode with the waveforms I've been describing. Switch it right and you get 3-wire with the LIN-like waveform. 

So if their @#$@#%@#$ installer installs the inside unit incorrectly, they need to flip the DIP switch.

(I say LIN-like because while my UTY-TFNXZ2 magically started communicating with the ASU30RLE once I switched over to 3-wire mode, which I assume means it's LIN because I assume that's what the UTY-TFNXZ2 talks, I haven't actually passed it through the MCP2025 to confirm)

**Comment by jaroslawprzybylowicz** [comment]
Thanks for sharing. Looking at those waveforms again (and the videos, I think they weren't there yesterday?), it's entirely possible that if you remove the AC high frequency component, you will get the same protocol.

Good to hear DIP switched worked for you. For the record, this is not LIN protocol per se. It's electrically compatible, but is not following the spec (shorter frames, different preambles and magic values).
